Repository MCCTeam/Minecraft-Console-Client, pull requests merged in 2022-09, with the labels that each got.

#2120 [1.19] Added Entity, Block, Material and Item palettes, Enabled Entity and Inventory handling + Fixed a bug
  MinecraftClient/Inventory/ItemPalettes/ItemPalette115.cs
  MinecraftClient/Inventory/ItemPalettes/ItemPalette1161.cs
  MinecraftClient/Inventory/ItemPalettes/ItemPalette1162.cs
  MinecraftClient/Inventory/ItemPalettes/ItemPalette117.cs
  MinecraftClient/Inventory/ItemPalettes/ItemPalette118.cs
  MinecraftClient/Inventory/ItemPalettes/ItemPalette119.cs
  MinecraftClient/Inventory/ItemType.cs
  MinecraftClient/Mapping/BlockPalettes/Palette113.cs
  MinecraftClient/Mapping/BlockPalettes/Palette114.cs
  MinecraftClient/Mapping/BlockPalettes/Palette115.cs
  MinecraftClient/Mapping/BlockPalettes/Palette116.cs
  MinecraftClient/Mapping/BlockPalettes/Palette117.cs
  MinecraftClient/Mapping/BlockPalettes/Palette119.cs
  MinecraftClient/Mapping/EntityPalettes/EntityPalette119.cs
  MinecraftClient/Mapping/EntityType.cs
  MinecraftClient/Mapping/Material.cs
  MinecraftClient/Mapping/Material2Tool.cs
  MinecraftClient/Mapping/MaterialExtensions.cs
  MinecraftClient/Protocol/Handlers/DataTypes.cs
  MinecraftClient/Protocol/Handlers/Protocol18.cs
Labels: a:enhancement, a:bugfix

#2114 Allow newer SSL/TLS protocol versions
  MinecraftClient/config/ChatBots/DiscordWebhook.cs
Labels: a:enhancement, a:bugfix

#2123 Basic support for 1.19.1 / 1.19.2
  MinecraftClient/Mapping/Dimension.cs
  MinecraftClient/Mapping/MaterialExtensions.cs
  MinecraftClient/Mapping/World.cs
  MinecraftClient/McClient.cs
  MinecraftClient/Program.cs
  MinecraftClient/Protocol/Handlers/DataTypes.cs
  MinecraftClient/Protocol/Handlers/PacketPalettes/PacketPalette119.cs
  MinecraftClient/Protocol/Handlers/PacketPalettes/PacketPalette1192.cs
  MinecraftClient/Protocol/Handlers/PacketType18Handler.cs
  MinecraftClient/Protocol/Handlers/PacketTypesIn.cs
  MinecraftClient/Protocol/Handlers/PacketTypesOut.cs
  MinecraftClient/Protocol/Handlers/Protocol16.cs
  MinecraftClient/Protocol/Handlers/Protocol18.cs
  MinecraftClient/Protocol/IMinecraftCom.cs
  MinecraftClient/Protocol/IMinecraftComHandler.cs
  MinecraftClient/Protocol/Message/ChatMessage.cs
  MinecraftClient/Protocol/Message/ChatParser.cs
  MinecraftClient/Protocol/Message/LastSeenMessageList.cs
  MinecraftClient/Protocol/PlayerInfo.cs
  MinecraftClient/Protocol/ProfileKey/KeyUtils.cs
  MinecraftClient/Protocol/ProfileKey/PlayerKeyPair.cs
  MinecraftClient/Protocol/ProfileKey/PrivateKey.cs
  MinecraftClient/Protocol/ProfileKey/PublicKey.cs
  MinecraftClient/Protocol/ProtocolHandler.cs
  MinecraftClient/Resources/lang/en.ini
  MinecraftClient/Scripting/ChatBot.cs
Labels: a:enhancement, a:new-feature

#2124 Bug fix & Performance Optimization
  MinecraftClient/ChatBots/ChatLog.cs
  MinecraftClient/Commands/Move.cs
  MinecraftClient/ConsoleIO.cs
  MinecraftClient/Crypto/AesCfb8Stream.cs
  MinecraftClient/Crypto/CryptoHandler.cs
  MinecraftClient/Crypto/FastAes.cs
  MinecraftClient/Crypto/IAesStream.cs
  MinecraftClient/Crypto/Streams/BouncyAes/AesFastEngine.cs
  MinecraftClient/Crypto/Streams/BouncyAes/BufferedBlockCipher.cs
  MinecraftClient/Crypto/Streams/BouncyAes/BufferedCipherBase.cs
  MinecraftClient/Crypto/Streams/BouncyAes/CfbBlockCipher.cs
  MinecraftClient/Crypto/Streams/BouncyAes/Check.cs
  MinecraftClient/Crypto/Streams/BouncyAes/CipherStream.cs
  MinecraftClient/Crypto/Streams/BouncyAes/CryptoException.cs
  MinecraftClient/Crypto/Streams/BouncyAes/DataLengthException.cs
  MinecraftClient/Crypto/Streams/BouncyAes/IBlockCipher.cs
  MinecraftClient/Crypto/Streams/BouncyAes/IBufferedCipher.cs
  MinecraftClient/Crypto/Streams/BouncyAes/ICipherParameters.cs
  MinecraftClient/Crypto/Streams/BouncyAes/KeyParameter.cs
  MinecraftClient/Crypto/Streams/BouncyAes/OutputLengthException.cs
  MinecraftClient/Crypto/Streams/BouncyAes/Pack.cs
  MinecraftClient/Crypto/Streams/BouncyAes/ParametersWithIV.cs
  MinecraftClient/Crypto/Streams/MonoAesStream.cs
  MinecraftClient/Crypto/Streams/RegularAesStream.cs
  MinecraftClient/Mapping/Block.cs
  MinecraftClient/Mapping/Chunk.cs
  MinecraftClient/Mapping/ChunkColumn.cs
  MinecraftClient/Mapping/Location.cs
  MinecraftClient/Mapping/Movement.cs
  MinecraftClient/Mapping/World.cs
  MinecraftClient/McClient.cs
  MinecraftClient/MinecraftClient.csproj
  MinecraftClient/Program.cs
  MinecraftClient/Protocol/Handlers/Compression/Inflate.cs
  MinecraftClient/Protocol/Handlers/Compression/Zlib.cs
  MinecraftClient/Protocol/Handlers/Compression/ZlibBaseStream.cs
  MinecraftClient/Protocol/Handlers/Compression/ZlibCodec.cs
  MinecraftClient/Protocol/Handlers/Compression/ZlibStream.cs
  MinecraftClient/Protocol/Handlers/DataTypes.cs
  MinecraftClient/Protocol/Handlers/Protocol16.cs
  MinecraftClient/Protocol/Handlers/Protocol18.cs
  MinecraftClient/Protocol/Handlers/Protocol18Forge.cs
  MinecraftClient/Protocol/Handlers/Protocol18Terrain.cs
  MinecraftClient/Protocol/Handlers/SocketWrapper.cs
  MinecraftClient/Protocol/Handlers/ZlibUtils.cs
  MinecraftClient/Protocol/IMinecraftCom.cs
  MinecraftClient/Protocol/Message/ChatParser.cs
  MinecraftClient/Protocol/PlayerInfo.cs
  MinecraftClient/Protocol/ProfileKey/KeyUtils.cs
  MinecraftClient/Protocol/ProfileKey/KeysCache.cs
  MinecraftClient/Protocol/ProfileKey/PlayerKeyPair.cs
  MinecraftClient/Protocol/ProfileKey/PublicKey.cs
  MinecraftClient/Protocol/Session/SessionCache.cs
  MinecraftClient/Protocol/Session/SessionToken.cs
  MinecraftClient/Resources/config/MinecraftClient.ini
  MinecraftClient/Settings.cs
Labels: a:bugfix

#2154 Support for using relative coordinates in /move
  MinecraftClient/Command.cs
  MinecraftClient/Commands/Move.cs
  MinecraftClient/Mapping/Location.cs
  MinecraftClient/Mapping/Movement.cs
  MinecraftClient/McClient.cs
Labels: a:enhancement

#2112 Fixed the Docker image.
  Docker/Dockerfile
  Docker/start-latest.sh
Labels: a:bugfix

#2174 Implemented the Follow Player chat bot.
  MinecraftClient/ChatBots/FollowPlayer.cs
  MinecraftClient/McClient.cs
  MinecraftClient/Resources/config/MinecraftClient.ini
  MinecraftClient/Resources/lang/en.ini
  MinecraftClient/Settings.cs
Labels: a:new-feature

#2214 Upated AutoAttack bot
  MinecraftClient/ChatBots/AutoAttack.cs
  MinecraftClient/Mapping/EntityTypeExtensions.cs
  MinecraftClient/Resources/config/MinecraftClient.ini
  MinecraftClient/Resources/lang/en.ini
  MinecraftClient/Settings.cs
Labels: a:enhancement, a:new-feature, in:auto-attack

#2215 Map Chat Bot
  MinecraftClient/ChatBots/Map.cs
  MinecraftClient/McClient.cs
  MinecraftClient/Resources/config/MinecraftClient.ini
  MinecraftClient/Resources/lang/en.ini
  MinecraftClient/Settings.cs
Labels: a:new-feature

#2218 Updated Anti AFK Bot to have Terrain Handling and random intervals option
  MinecraftClient/ChatBots/AntiAFK.cs
  MinecraftClient/McClient.cs
  MinecraftClient/Resources/config/MinecraftClient.ini
  MinecraftClient/Resources/lang/en.ini
  MinecraftClient/Settings.cs
Labels: a:enhancement, a:new-feature
